# Generated by Django 5.0.6 on 2025-01-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
    ]
