# Generated by Django 5.0.6 on 2025-01-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_table_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='image',
            field=models.ImageField(upload_to='posts_Image/'),
        ),
    ]
